ReactiveShipping::Carriers.register :BTVP, 'reactive_freight/carriers/btvp'
ReactiveShipping::Carriers.register :CTBV, 'reactive_freight/carriers/ctbv'
ReactiveShipping::Carriers.register :DPHE, 'reactive_freight/carriers/dphe'
ReactiveShipping::Carriers.register :RDFS, 'reactive_freight/carriers/rdfs'
ReactiveShipping::Carriers.register :WRDS, 'reactive_freight/carriers/wrds'
